scaffold_policy_name='tf_docker'
pkg_name='tf_docker'
pkg_origin="winhab"
pkg_version="0.1.5"
pkg_maintainer="Jeff Brimager <jeff.brimager@chef.io>"
pkg_license="docker-2.0"
pkg_description="Effortless package for terffaform docker server"
pkg_upstream_url="http://chef.io"
pkg_scaffolding="chef/scaffolding-chef-infra"
